//Display Name
export const TOP_TRENDING_IDEAS = 'Top Trending Ideas';
export const TOP_CONSTRIBUTORS = 'Top Contributors';
export const IDEA_SUBJECT = 'Idea Subject';
export const IDEA_TYPE = 'Idea Type';
export const SUBMITTED_BY = 'Submitted by';
export const IDEA_CATEGORY = 'Idea Category';
export const SUBMITTED_ON = 'Submitted on';
export const IDEA_STATUS = 'Status';
export const LIKES = 'Likes';
export const SUBMITTED_IDEAS = 'Submitted Ideas';
export const APPROVED_IDEAS = 'Approved Ideas';
export const SUBMITTED = 'Submitted';
export const APPROVED = 'Approved';
export const DEVELOPMENT = 'Development';
export const COMPLETED = 'Completed';
export const COMPLETE = 'Complete';
export const DRAFT = 'Draft';
export const REVIEW = 'Review';
export const CLOSED = 'Closed';
export const CLOSE = 'Close';
export const MONTH = 'Month';
export const YEAR = 'Year';
export const QUARTER = 'Quarter';
export const ALL = 'All';
export const SUCCESS = 'success';
export const GET_MYIDEAS_DETAIL = 'Get My Ideas';
export const ACTIVE = 'Active';
export const DEACTIVATED = 'Deactivated';
export const RECENTLY_SUBMITTED_IDEAS = 'Recently Submitted Ideas';
export const ALL_IDEAS = 'All Ideas';
export const DEFAULT_PAGE_SIZE = 10;
export const STATUS = 'Status';
export const USERS ="Users";
export const XEBIAOFFICE ="Xebia Office";
export const ROLE ="Role";
export const JOINEDON ="Joined On";


